### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by outlier009** [seandavi/sars2pack#17]
I have tried several times to install but failed

**Comment by kotliary** [comment]
Hi,
I also had problems installing it. Ended up with the following.
Used BioManager::install, it installs from the github anyway.
When given selection to update packages choose 3 (None).
Then if the installation complains about certain packages I installed it from source:
install.packages('packagename", type=source")
Then repeated.
Also I remember I had to remove 00LOCK directory from R' library directory a few of times after broken installation.

**Comment by seandavi** [comment]
Thanks, @kotliary, for helping out. @outlier009, did you get things installed? If not, can you paste in the errors you are getting, the version of R you are using, your operating system, and the commands you are trying?

**Comment by outlier009** [comment]
My operation system is windows 10 home edition version 1909 and R  version is 3.6.3 (2020-02-29).

**Comment by seandavi** [comment]
I'm going to close for now, but if you have problems again, just reopen or put in a new issue.
