### ISSUE TITLE
[New Data Resource]: https://github.com/COVID19StatePolicy/SocialDistancing

### ISSUE THREAD

**Issue by mymil** [seandavi/sars2pack#28]
**Description**

> This is a routinely-maintained data repository for US state-level distancing policies to the 2019 novel coronavirus (SARS-CoV-2), the cause of COVID-19. It was developed and is maintained by researchers at the University of Washington, Seattle, WA, USA. 

These data will be useful for US state-level modeling, for example implementing the [Imperial College covid19model](https://github.com/ImperialCollegeLondon/covid19model)

**Access details**
- URL: https://github.com/COVID19StatePolicy/SocialDistancing
- Format: .csv
- Open access: [ X ] Yes or [ ] No (include additional information)

**Data elements**
- **File**: "USstatesCov19distancingpolicy.csv". Prior datasets are archived with date stamps in the format of YYYYMMDD.
- **location_id**: State-level unique identifier per the Global Burden of Disease (GBD) study.  
- **StateFIPS**: State-level Federal Information Processing Standard (FIPS) code.    
- **StatePostal**: Two-letter state postal code. This corresponds to StatePostal in the "state_id.csv".
- **StateName**: State name. This corresponds to StateName in "state_id.csv".
- **StatePolicy** : String variable of state policies, as described below:   
      - **EmergDec**: Emergency declaration; currently includes State of Emergency, Public Health Emergency, and Public Health Disaster declarations.     
      - **GathRecomAny**: Any recommendation of against gathering that stops short of a formal mandate or restriction of gatherings.  Includes uses phrasing such as "advises against mass gatherings" and "constituents should avoid gatherings of more than 100" that imply a recommendation versus restriction.    
      - **GathRestrictAny**: Restriction of any gathering; includes formal mandate or an executive order that uses phrasing such as "prohibits all mass gatherings" (per definition of mass gathering) and "constituents must avoid gatherings of more than 100". The first issuance of a gathering restriction of any size is coded with this date.      
      - **GathRestrict1000**: Restriction of any gathering exceeding 1000 persons; coding followed the "GathRestrict" criteria. Some mandates include exceptions for essential businesses and organizations; these cases are still coded as a restriction applicable to the general public.     
       - **GathRestrict500**: Restriction of any gathering exceeding 500 persons; coding followed the "GathRestrict" criteria and used the same coding approach as "GathRestrict1000" (i.e., considered a restriction if applicable to the general public).      
       - **GathRestrict250**: Restriction of any gathering exceeding 250 persons; coding followed the same criteria as above.    
       - **GathRestrict100**: Restriction of any gathering exceeding 100 persons; coding followed the same criteria as above.    
       - **GathRestrict50**: Restriction of any gathering exceeding 50 persons; coding followed the same criteria as above.    
       - **GathRestrict25**: Restriction of any gathering exceeding 25 persons; coding followed the same criteria as above.         
       - **GathRestrict10**: Restriction of any gathering exceeding 10 persons; coding followed the same criteria as above.    
       - **GathRestrict5**: Restriction of any gathering exceeding 5 persons; coding followed the same criteria as above.    
       - **SchoolClose**: Formal closing of (at minimum) public schools. Where possible, additional information on types of school closings are provided in "PolicyCodingNotes".      
       - **RestaurantRestrict**: Restriction or limitation of restaurants and other venues where food is consumed on-premises. Coding a case as a restriction requires a formal restriction on operations (e.g., offsite consumption only, limiting services to only take-away, delivery, or curbside drop-off) or mandate for substantially reducing operations (e.g., restaurant closure must occur unless 10 or fewer patrons are dining at at time).      
       - **OtherBusinessClose**: Mandate to fully close operations of any category of business. Coding a case as an other business closure requires the executive order to use phrasing indicative of a mandate (e.g., "casinos must close", "operations at fitness centers and entertainment venues must cease by *date*"). A given state may have multiple cases of other business closures as they often occurred in phases (e.g., fitness centers and gyms on March 13, 2020; casinos and entertainment venues on March 15, 2020; personal service businesses like barbers and nail salons on March 19, 2020); thus, where possible, separate entries are provided for each mandate.    
       - **NEBusinessClose**: Mandate to close all non-essential businesses. Coding a case as a closure order requires the executive order to use phrasing indicative of a mandate (e.g., "non-essential businesses are required to close", "non-essential businesses must cease operations by *date*"). Coding does not distinguish among states' classification of essential versus non-essential businesses, as they vary substantially by state.      
       - **StayAtHome**: Mandate for individuals to stay at home for all non-essential activities. Coding a case as a stay-at-home order mandate requires the executive order to using phrasing indicative of a mandate (e.g., "must stay at home"); otherwise it is coded as 0 for the "Mandate" variable if it uses advisory phrasing. Coding does not distinguish among states' classification of essential versus non-essential activities, as they vary substantially by state. Shelter-in-place and stay-at-home orders are considered to be equivalent.       
       - **StateCurfew**: Mandates specific curfews at which residents are not to be outside their homes unless performing essential activities, as defined by the state. Coding a case as a state curfew requires specific curfew times (thus "stay-at-home" mandates were not considered curfews).      
       -**Quarantine**: Quarantines mandated for people entering the state, requiring a period of self-isolation. Quarantines may be imposed on all people entering the state, out-of-state residents, or travelers from a particular state or city. Quarantine length and who is covered by the policy can be found in the "PolicyNotes" variable. This policy type was added April 3, 2020.    
       -**TravelRestrictIntra**: Restrictions on travel within the state. These restrictions can be between cities or counties or within them. The "StateWide" variable reflects whether these restrictions are applicable to across the state (coded as 1) or only for local areas (coded as 0). This policy type was added April 3, 2020.  
       -**TravelRestrictExit**: Policies which prohibit residents of a state from leaving the state. These policies may have exceptions for essential businesses. This policy type was added April 3, 2020.    
       - **TravelRestrictEntry**: Travel restriction mandates that limit non-residents from entering a given state. These policies may have exceptions or exemptions for essential businesses or their employees, and they may include restrictions for commercial lodging for non-residents. This policy type was added April 8, 2020.   
- **Mandate**: Binary variable indicating whether the policy applied is a mandate (1) or is advisory or a recommendation (0). This is coded on the basis of the order's phrasing (e.g., "residents are advised to stay at home and avoid unnecessary travel" would be coded as 0 for mandate as a "StayAtHome" policy). This variable was added on March 30, 2020.   
- **DateIssued**: Date of policy issuance. The date of signing of the policy document (e.g., executive order) was used wherever possible. Format is YYYYMMDD (e.g., March 16, 2020 is 20200316). Entries are not currently included for most non-statewide policies; this documentation is in-progress.  
- **DateEnacted**: Date of policy enactment: the date of when the policy would be enforced, per descriptions available in policy documents. The format is YYYYMMDD. Entries are not currently included for most non-statewide policies; this documentation is in-progress.  
- **DateExpiry**: Date of policy expiry, if or as provided in the policy issuance or executive order. This date is meant to reflect when the policy or order would be in effect until or unless additional action is taken to extend, amend, or halt its status. The format is YYYYMMDD. This documentation is in-progress, as it was added on March 29, 2020 as a variable of interest.    
- **DateEnded**: Date the policy is ended. This date is meant to reflect when a policy is ended, particularly if it is halted or reversed prior to its expiry date. The format is YYYYMMDD. This documentation is in-progress.    
- **PolicyCodingNotes**: Coder notes. Information on specific businesses closed, type of emergency declaration, potential exceptions, etc., are provided here. 
- **PolicySource**: Currently available source for each policy issued. Sourcing by hard-copy PDF _versus_ hyperlinks is in-progress.    
- **StateWide**: Binary variable indicating whether the policy applied statewide (1) or for local areas (0).   
- **LastUpdated**: Date of last update for the given state-policy observation. The format is YYYYMMDD.    
- **LastUpdatedNotes**: Coder notes on last updates. This reflects notable changes since the last update, especially if a date has been recoded (e.g., switching to coding orders enacted at 11:59 pm on date1 to date1+1 for its enactment timing) or the "StatePolicy" type has been amended (e.g., some initial coding of "NEBusinessClose" policies were applicable to non-essential in-person retail businesses only, not all non-essential businessess as defined by state).

**Comment by seandavi** [comment]
Thanks, @mymil. Nice addition and thanks for making it so easy with the nice issue.
