### ISSUE TITLE
cdc_excess_deaths dates may have changed format

### ISSUE THREAD

**Issue by nhansen** [seandavi/sars2pack#49]
Hi Sean,

I love this package! I noticed tonight that when I call cdc_excess_deaths, the dates aren't parsing correctly unless I use ymd rather than mdy on the "date" (Week Ending Date) column. Looks like the CDC's format might have changed on you?

Thanks again for making covid data analysis with R so simple,
--Nancy

**Comment by seandavi** [comment]
Thanks, @nhansen. 

Fixed in 0403f45.
